name: Bug report
description: Report a problem with naamase-api
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect?
      placeholder: Clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Command run
        2. Config used (redact secrets)
        3. Output/logs
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste relevant logs (redact secrets)
      render: shell
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: Output of `bun --version` and commit SHA
